### ISSUE TITLE
CanaryHTTPMonitor CRD

### ISSUE THREAD

**Issue by JossWhittle** [SwanseaUniversityMedical/Canary#2]
This will be a kubernetes custom resource definition for a `CanaryHTTPMonitor` type.

It represents a HTTP endpoint to be polled by the DaemonSet of controller pods running on each node.

Potentially what one of these could look like. 

```
apiVersion: "canary.ukserp.ac.uk/v1"
kind: CanaryHTTPMonitor
metadata:
  name: github
  namespace: canary
spec:
  url: https://api.github.com/octocat
  interval: 30 #seconds
  expect:
    status: 200
```

I kept `spec.expect` as a dict in case we later wanted to add a rule to test a regex against what comes back. Right now we should test for the status code of the http request. This could be a single value as shown, or a list of numbers.

- [x] #13
